version: 2.1

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    parameters:
      commit-desc:
        type: string
        default: $CIRCLE_BRANCH
    steps:
      - checkout
      - run: echo $(CIRCLE_BRANCH)
      - when:
          condition:
            matches:
              pattern: "^master$"
              value: $CIRCLE_BRANCH
          steps:
            - run: echo "I am on master"

workflows:
  my-workflow:
    jobs:
      - my-job
