version: 2.1
parameters:
  commit-desc:
    type: string
    default: $(echo $CIRCLE_BRANCH)
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo << pipeline.parameters.commit-desc >>
      - when:
          condition:
            matches:
              pattern: "master"
              value: << pipeline.parameters.commit-desc >>
          steps:
            - run: echo "I am on master"

workflows:
  my-workflow:
    jobs:
      - my-job
